/* Generated by tools/gen_runtime_tables.py from map/ui-map. Don't edit. */
#ifndef W2S_MAP_TABLES_H
#define W2S_MAP_TABLES_H

struct w2s_map_entry
{
    const char *id;
    const UINT *state_in;
    unsigned int state_in_count;
    const UINT *answers;
    unsigned int answers_count;
};

static const UINT w2s_state_button_push[] = { WM_SETTEXT, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, BM_SETCHECK, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_default[] = { WM_SETTEXT, WM_ENABLE, BM_SETSTYLE, DM_SETDEFID, WM_SETFONT, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, BM_SETCHECK, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_checkbox[] = { WM_SETTEXT, WM_ENABLE, BM_SETCHECK, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_3state[] = { BM_SETCHECK, WM_SETTEXT, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_pushlike[] = { BM_SETCHECK, WM_SETTEXT, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_radio[] = { BM_SETCHECK, WM_SETTEXT, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_groupbox[] = { WM_SETTEXT, WM_WINDOWPOSCHANGED, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, BM_SETCHECK, BCM_SETSPLITINFO, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_split[] = { WM_SETTEXT, BCM_SETSPLITINFO, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, BM_SETCHECK, WM_WINDOWPOSCHANGED, BCM_SETNOTE, BCM_SETSHIELD };
static const UINT w2s_state_button_commandlink[] = { WM_SETTEXT, BCM_SETNOTE, BCM_SETSHIELD, WM_ENABLE, WM_SETFONT, BM_SETSTYLE, BM_SETSTATE, BM_SETIMAGE, BM_CLICK, DM_SETDEFID, BM_SETCHECK, WM_WINDOWPOSCHANGED, BCM_SETSPLITINFO };
static const UINT w2s_state_static_text[] = { WM_SETTEXT, WM_SETFONT, WM_ENABLE, STM_SETICON, STM_SETIMAGE };
static const UINT w2s_state_static_image[] = { STM_SETICON, STM_SETIMAGE, WM_SETTEXT, WM_SETFONT, WM_ENABLE };
static const UINT w2s_state_static_separator[] = { WM_SETTEXT, WM_SETFONT, WM_ENABLE, STM_SETICON, STM_SETIMAGE };
static const UINT w2s_state_static_frame[] = { WM_SETTEXT, WM_SETFONT, WM_ENABLE, STM_SETICON, STM_SETIMAGE };
static const UINT w2s_state_edit_single[] = { WM_SETTEXT, EM_SETSEL, EM_REPLACESEL, EM_SETREADONLY, EM_SETLIMITTEXT, EM_SETCUEBANNER, EM_SETPASSWORDCHAR, EM_UNDO, EM_SCROLLCARET, EM_LINESCROLL, WM_CUT, WM_PASTE, WM_CLEAR };
static const UINT w2s_answers_edit_single[] = { EM_SHOWBALLOONTIP, EM_HIDEBALLOONTIP };
static const UINT w2s_state_edit_password[] = { WM_SETTEXT, EM_SETPASSWORDCHAR, EM_SETSEL, EM_REPLACESEL, EM_SETREADONLY, EM_SETLIMITTEXT, EM_SETCUEBANNER, EM_UNDO, EM_SCROLLCARET, EM_LINESCROLL, WM_CUT, WM_PASTE, WM_CLEAR };
static const UINT w2s_answers_edit_password[] = { EM_SHOWBALLOONTIP, EM_HIDEBALLOONTIP };
static const UINT w2s_state_edit_number[] = { WM_SETTEXT, EM_SETSEL, EM_REPLACESEL, EM_SETREADONLY, EM_SETLIMITTEXT, EM_SETCUEBANNER, EM_SETPASSWORDCHAR, EM_UNDO, EM_SCROLLCARET, EM_LINESCROLL, WM_CUT, WM_PASTE, WM_CLEAR };
static const UINT w2s_answers_edit_number[] = { EM_SHOWBALLOONTIP, EM_HIDEBALLOONTIP };
static const UINT w2s_state_edit_readonly[] = { WM_SETTEXT, EM_SETREADONLY, EM_SETSEL, EM_REPLACESEL, EM_SETLIMITTEXT, EM_SETCUEBANNER, EM_SETPASSWORDCHAR, EM_UNDO, EM_SCROLLCARET, EM_LINESCROLL, WM_CUT, WM_PASTE, WM_CLEAR };
static const UINT w2s_state_edit_multiline[] = { WM_SETTEXT, EM_SETSEL, EM_REPLACESEL, EM_SCROLLCARET, EM_LINESCROLL, EM_SETREADONLY, EM_SETLIMITTEXT, EM_UNDO, WM_CUT, WM_PASTE, WM_CLEAR, EM_SETCUEBANNER, EM_SETPASSWORDCHAR };
static const UINT w2s_answers_edit_multiline[] = { EM_GETSEL, EM_LINEFROMCHAR, EM_LINEINDEX, EM_GETLINECOUNT, EM_POSFROMCHAR, EM_LINELENGTH, EM_GETFIRSTVISIBLELINE, EM_GETLINE, EM_CHARFROMPOS };
static const UINT w2s_state_edit_balloon[] = { WM_SETTEXT, EM_SETSEL, EM_REPLACESEL, EM_SETREADONLY, EM_SETLIMITTEXT, EM_SETCUEBANNER, EM_SETPASSWORDCHAR, EM_UNDO, EM_SCROLLCARET, EM_LINESCROLL, WM_CUT, WM_PASTE, WM_CLEAR };
static const UINT w2s_state_listbox_single[] = { LB_ADDSTRING, LB_INSERTSTRING, LB_DELETESTRING, LB_RESETCONTENT, LB_SETCURSEL, LB_SETTOPINDEX, LB_SETITEMDATA, WM_SETREDRAW, LB_SETSEL, LB_SELITEMRANGE, LB_SETANCHORINDEX, LB_SETCARETINDEX, LB_SETCOLUMNWIDTH };
static const UINT w2s_state_listbox_multi[] = { LB_SETSEL, LB_SELITEMRANGE, LB_SETANCHORINDEX, LB_SETCARETINDEX, LB_ADDSTRING, LB_INSERTSTRING, LB_DELETESTRING, LB_RESETCONTENT, LB_SETCURSEL, LB_SETTOPINDEX, LB_SETITEMDATA, WM_SETREDRAW, LB_SETCOLUMNWIDTH };
static const UINT w2s_state_listbox_multicolumn[] = { LB_SETCOLUMNWIDTH, LB_ADDSTRING, LB_INSERTSTRING, LB_DELETESTRING, LB_RESETCONTENT, LB_SETCURSEL, LB_SETTOPINDEX, LB_SETITEMDATA, WM_SETREDRAW, LB_SETSEL, LB_SELITEMRANGE, LB_SETANCHORINDEX, LB_SETCARETINDEX };
static const UINT w2s_state_listbox_nosel[] = { LB_ADDSTRING, LB_INSERTSTRING, LB_DELETESTRING, LB_RESETCONTENT, LB_SETCURSEL, LB_SETTOPINDEX, LB_SETITEMDATA, WM_SETREDRAW, LB_SETSEL, LB_SELITEMRANGE, LB_SETANCHORINDEX, LB_SETCARETINDEX, LB_SETCOLUMNWIDTH };
static const UINT w2s_state_combobox_dropdownlist[] = { CB_ADDSTRING, CB_INSERTSTRING, CB_DELETESTRING, CB_RESETCONTENT, CB_SETCURSEL, CB_SELECTSTRING, CB_SHOWDROPDOWN, WM_SETTEXT, CB_SETEDITSEL, CB_LIMITTEXT, WM_COMMAND };
static const UINT w2s_state_combobox_editable[] = { WM_SETTEXT, CB_ADDSTRING, CB_INSERTSTRING, CB_DELETESTRING, CB_RESETCONTENT, CB_SETCURSEL, CB_SELECTSTRING, CB_SETEDITSEL, CB_LIMITTEXT, WM_COMMAND, CB_SHOWDROPDOWN };
static const UINT w2s_state_combobox_simple[] = { CB_ADDSTRING, CB_INSERTSTRING, CB_DELETESTRING, CB_RESETCONTENT, CB_SETCURSEL, CB_SELECTSTRING, CB_SHOWDROPDOWN, WM_SETTEXT, CB_SETEDITSEL, CB_LIMITTEXT, WM_COMMAND };
static const UINT w2s_state_comboboxex[] = { CBEM_INSERTITEMA, CBEM_INSERTITEMW, CBEM_SETITEMA, CBEM_SETITEMW, CBEM_DELETEITEM, CBEM_SETIMAGELIST, CB_SETCURSEL, CB_RESETCONTENT, WM_SETTEXT, WM_COMMAND };
static const UINT w2s_state_listview_report[] = { LVM_INSERTCOLUMNA, LVM_INSERTCOLUMNW, LVM_SETCOLUMNA, LVM_SETCOLUMNW, LVM_DELETECOLUMN, LVM_INSERTITEMA, LVM_INSERTITEMW, LVM_SETITEMA, LVM_SETITEMW, LVM_SETITEMTEXTA, LVM_SETITEMTEXTW, LVM_DELETEITEM, LVM_DELETEALLITEMS, LVM_SETITEMSTATE, LVM_SORTITEMS, LVM_SORTITEMSEX, LVM_ENSUREVISIBLE, LVM_SETCOLUMNWIDTH, LVM_SETITEMCOUNT, LVM_SETIMAGELIST, LVM_ARRANGE, LVM_SETICONSPACING, LVM_ENABLEGROUPVIEW, LVM_INSERTGROUP, LVM_SETGROUPINFO };
static const UINT w2s_state_listview_icon[] = { LVM_SETIMAGELIST, LVM_ARRANGE, LVM_SETICONSPACING, LVM_INSERTITEMA, LVM_INSERTITEMW, LVM_SETITEMA, LVM_SETITEMW, LVM_SETITEMTEXTA, LVM_SETITEMTEXTW, LVM_DELETEITEM, LVM_DELETEALLITEMS, LVM_SETITEMSTATE, LVM_SORTITEMS, LVM_SORTITEMSEX, LVM_SETITEMCOUNT, LVM_ENSUREVISIBLE, LVM_INSERTCOLUMNA, LVM_INSERTCOLUMNW, LVM_SETCOLUMNA, LVM_SETCOLUMNW, LVM_DELETECOLUMN, LVM_SETCOLUMNWIDTH, LVM_ENABLEGROUPVIEW, LVM_INSERTGROUP, LVM_SETGROUPINFO };
static const UINT w2s_state_listview_list[] = { LVM_INSERTITEMA, LVM_INSERTITEMW, LVM_SETITEMA, LVM_SETITEMW, LVM_SETITEMTEXTA, LVM_SETITEMTEXTW, LVM_DELETEITEM, LVM_DELETEALLITEMS, LVM_SETITEMSTATE, LVM_SORTITEMS, LVM_SORTITEMSEX, LVM_SETITEMCOUNT, LVM_ENSUREVISIBLE, LVM_INSERTCOLUMNA, LVM_INSERTCOLUMNW, LVM_SETCOLUMNA, LVM_SETCOLUMNW, LVM_DELETECOLUMN, LVM_SETCOLUMNWIDTH, LVM_SETIMAGELIST, LVM_ARRANGE, LVM_SETICONSPACING, LVM_ENABLEGROUPVIEW, LVM_INSERTGROUP, LVM_SETGROUPINFO };
static const UINT w2s_state_listview_checkboxes[] = { LVM_SETITEMSTATE, LVM_INSERTCOLUMNA, LVM_INSERTCOLUMNW, LVM_SETCOLUMNA, LVM_SETCOLUMNW, LVM_DELETECOLUMN, LVM_SETCOLUMNWIDTH, LVM_INSERTITEMA, LVM_INSERTITEMW, LVM_SETITEMA, LVM_SETITEMW, LVM_SETITEMTEXTA, LVM_SETITEMTEXTW, LVM_DELETEITEM, LVM_DELETEALLITEMS, LVM_SORTITEMS, LVM_SORTITEMSEX, LVM_SETITEMCOUNT, LVM_ENSUREVISIBLE, LVM_SETIMAGELIST, LVM_ARRANGE, LVM_SETICONSPACING, LVM_ENABLEGROUPVIEW, LVM_INSERTGROUP, LVM_SETGROUPINFO };
static const UINT w2s_state_listview_groups[] = { LVM_ENABLEGROUPVIEW, LVM_INSERTGROUP, LVM_SETGROUPINFO, LVM_INSERTCOLUMNA, LVM_INSERTCOLUMNW, LVM_SETCOLUMNA, LVM_SETCOLUMNW, LVM_DELETECOLUMN, LVM_INSERTITEMA, LVM_INSERTITEMW, LVM_SETITEMA, LVM_SETITEMW, LVM_SETITEMTEXTA, LVM_SETITEMTEXTW, LVM_DELETEITEM, LVM_DELETEALLITEMS, LVM_SETITEMSTATE, LVM_SORTITEMS, LVM_SORTITEMSEX, LVM_ENSUREVISIBLE, LVM_SETCOLUMNWIDTH, LVM_SETITEMCOUNT, LVM_SETIMAGELIST, LVM_ARRANGE, LVM_SETICONSPACING };
static const UINT w2s_state_listview_empty[] = { LVM_INSERTCOLUMNA, LVM_INSERTCOLUMNW, LVM_SETCOLUMNA, LVM_SETCOLUMNW, LVM_DELETECOLUMN, LVM_INSERTITEMA, LVM_INSERTITEMW, LVM_SETITEMA, LVM_SETITEMW, LVM_SETITEMTEXTA, LVM_SETITEMTEXTW, LVM_DELETEITEM, LVM_DELETEALLITEMS, LVM_SETITEMSTATE, LVM_SORTITEMS, LVM_SORTITEMSEX, LVM_ENSUREVISIBLE, LVM_SETCOLUMNWIDTH, LVM_SETITEMCOUNT, LVM_SETIMAGELIST, LVM_ARRANGE, LVM_SETICONSPACING, LVM_ENABLEGROUPVIEW, LVM_INSERTGROUP, LVM_SETGROUPINFO };
static const UINT w2s_state_treeview[] = { TVM_INSERTITEMA, TVM_INSERTITEMW, TVM_DELETEITEM, TVM_SETITEMA, TVM_SETITEMW, TVM_EXPAND, TVM_SELECTITEM, TVM_ENSUREVISIBLE, TVM_SETIMAGELIST, TVM_SORTCHILDREN, TVM_SORTCHILDRENCB };
static const UINT w2s_state_header[] = { HDM_INSERTITEMA, HDM_INSERTITEMW, HDM_SETITEMA, HDM_SETITEMW, HDM_LAYOUT };
static const UINT w2s_state_tab[] = { TCM_INSERTITEMA, TCM_INSERTITEMW, TCM_SETITEMA, TCM_SETITEMW, TCM_DELETEITEM, TCM_SETCURSEL, TCM_SETCURFOCUS };
static const UINT w2s_answers_tab[] = { TCM_ADJUSTRECT, TCM_GETITEMRECT };
static const UINT w2s_state_propsheet[] = { PSM_SETCURSEL, PSM_ADDPAGE, PSM_REMOVEPAGE, PSM_CHANGED, PSM_UNCHANGED, PSM_SETTITLEA, PSM_SETTITLEW, PSM_SETWIZBUTTONS };
static const UINT w2s_state_propsheet_wizard[] = { PSM_SETWIZBUTTONS, PSM_SETHEADERTITLEA, PSM_SETHEADERTITLEW, PSM_SETHEADERSUBTITLEA, PSM_SETHEADERSUBTITLEW, PSM_SETFINISHTEXTA, PSM_SETFINISHTEXTW, PSM_PRESSBUTTON };
static const UINT w2s_state_dialog[] = { WM_INITDIALOG, DM_SETDEFID, WM_NEXTDLGCTL };
static const UINT w2s_state_toolbar[] = { TB_ADDBUTTONSA, TB_ADDBUTTONSW, TB_INSERTBUTTONA, TB_INSERTBUTTONW, TB_DELETEBUTTON, TB_SETSTATE, TB_CHECKBUTTON, TB_ENABLEBUTTON, TB_HIDEBUTTON, TB_PRESSBUTTON, TB_SETIMAGELIST, TB_ADDBITMAP, TB_LOADIMAGES, TB_CHANGEBITMAP, TB_SETBUTTONINFOA, TB_SETBUTTONINFOW, TB_SETCMDID, TB_SETSTYLE, TB_SETEXTENDEDSTYLE, TB_SETBUTTONSIZE, TB_SETBITMAPSIZE, TB_AUTOSIZE, WM_LBUTTONUP, WM_SIZE, WM_PARENTNOTIFY, WM_WINDOWPOSCHANGED };
static const UINT w2s_state_rebar[] = { RB_INSERTBANDA, RB_INSERTBANDW, RB_SETBANDINFOA, RB_SETBANDINFOW, RB_DELETEBAND, RB_MAXIMIZEBAND, WM_SIZE, WM_PARENTNOTIFY };
static const UINT w2s_answers_rebar[] = { RB_SHOWBAND };
static const UINT w2s_state_statusbar[] = { SB_SETPARTS, SB_SETTEXTA, SB_SETTEXTW, SB_SIMPLE, SB_SETICON, SB_SETTIPTEXTA, SB_SETTIPTEXTW };
static const UINT w2s_state_pager[] = { 0 };
static const UINT w2s_state_mdiclient[] = { 0 };
static const UINT w2s_state_scrollbar[] = { SBM_SETSCROLLINFO, SBM_SETPOS, SBM_SETRANGE, SBM_ENABLE_ARROWS };
static const UINT w2s_state_progress[] = { PBM_SETPOS, PBM_DELTAPOS, PBM_STEPIT, PBM_SETRANGE, PBM_SETRANGE32, PBM_SETSTATE, PBM_SETMARQUEE, PBM_SETBARCOLOR };
static const UINT w2s_state_trackbar[] = { TBM_SETPOS, TBM_SETRANGE, TBM_SETRANGEMIN, TBM_SETRANGEMAX, TBM_SETTICFREQ, TBM_SETTIC, TBM_CLEARTICS, TBM_SETLINESIZE, TBM_SETPAGESIZE };
static const UINT w2s_state_trackbar_vertical[] = { TBM_SETPOS, TBM_SETRANGE, TBM_SETRANGEMIN, TBM_SETRANGEMAX, TBM_SETTICFREQ, TBM_SETTIC, TBM_CLEARTICS, TBM_SETLINESIZE, TBM_SETPAGESIZE };
static const UINT w2s_state_updown[] = { UDM_SETPOS32, UDM_SETRANGE32, UDM_SETPOS, UDM_SETRANGE, UDM_SETBUDDY, UDM_SETACCEL, UDM_SETBASE };
static const UINT w2s_state_datetime[] = { DTM_SETSYSTEMTIME, DTM_SETRANGE, DTM_SETFORMATA, DTM_SETFORMATW, DTM_SETMCCOLOR };
static const UINT w2s_state_monthcal[] = { MCM_SETCURSEL, MCM_SETRANGE, MCM_SETTODAY, MCM_SETFIRSTDAYOFWEEK };
static const UINT w2s_state_hotkey[] = { HKM_SETHOTKEY, HKM_SETRULES };
static const UINT w2s_state_ipaddress[] = { IPM_SETADDRESS, IPM_CLEARADDRESS, IPM_SETRANGE, IPM_SETFOCUS };
static const UINT w2s_state_syslink[] = { WM_SETTEXT, LM_SETITEM };
static const UINT w2s_state_animate[] = { ACM_OPENA, ACM_OPENW, ACM_PLAY, ACM_STOP };
static const UINT w2s_state_tooltip[] = { TTM_ADDTOOLA, TTM_ADDTOOLW, TTM_DELTOOLA, TTM_DELTOOLW, TTM_UPDATETIPTEXTA, TTM_UPDATETIPTEXTW, TTM_SETTOOLINFOA, TTM_SETTOOLINFOW, TTM_SETTITLEA, TTM_SETTITLEW, TTM_ACTIVATE, TTM_SETMAXTIPWIDTH, TTM_TRACKACTIVATE, TTM_TRACKPOSITION };
static const UINT w2s_state_tooltip_balloon[] = { TTM_TRACKACTIVATE, TTM_TRACKPOSITION, TTM_SETTITLEA, TTM_SETTITLEW, TTM_ADDTOOLA, TTM_ADDTOOLW, TTM_DELTOOLA, TTM_DELTOOLW, TTM_UPDATETIPTEXTA, TTM_UPDATETIPTEXTW, TTM_SETTOOLINFOA, TTM_SETTOOLINFOW, TTM_ACTIVATE, TTM_SETMAXTIPWIDTH };
static const UINT w2s_state_nativefont[] = { 0 };
static const UINT w2s_state_messagebox[] = { 0 };
static const UINT w2s_state_taskdialog[] = { TDM_SET_ELEMENT_TEXT, TDM_UPDATE_ELEMENT_TEXT, TDM_SET_PROGRESS_BAR_POS, TDM_SET_PROGRESS_BAR_STATE, TDM_SET_MARQUEE_PROGRESS_BAR, TDM_ENABLE_BUTTON, TDM_CLICK_BUTTON, TDM_CLICK_RADIO_BUTTON, TDM_CLICK_VERIFICATION };
static const UINT w2s_state_filedialog_open[] = { 0 };
static const UINT w2s_state_filedialog_save[] = { 0 };
static const UINT w2s_state_filedialog_folder[] = { 0 };
static const UINT w2s_state_colordialog[] = { 0 };
static const UINT w2s_state_fontdialog[] = { 0 };
static const UINT w2s_state_printdialog[] = { 0 };
static const UINT w2s_state_pagesetup[] = { 0 };
static const UINT w2s_state_findreplace[] = { 0 };
static const UINT w2s_state_shellabout[] = { 0 };
static const UINT w2s_state_rundialog[] = { 0 };
static const UINT w2s_state_pickicon[] = { 0 };
static const UINT w2s_state_restartdialog[] = { 0 };
static const UINT w2s_state_fileprogress[] = { 0 };
static const UINT w2s_state_menu_bar[] = { 0 };
static const UINT w2s_state_menu_popup[] = { 0 };
static const UINT w2s_state_menu_system[] = { 0 };
static const UINT w2s_state_window_frame[] = { 0 };
static const UINT w2s_state_tray[] = { 0 };
static const UINT w2s_state_notification[] = { 0 };
static const UINT w2s_state_taskbar_progress[] = { 0 };
static const UINT w2s_state_attention[] = { 0 };
static const UINT w2s_state_beep[] = { 0 };

static const struct w2s_map_entry w2s_map_entries[] =
{
    { "button.push", w2s_state_button_push, 13, NULL, 0 },
    { "button.default", w2s_state_button_default, 13, NULL, 0 },
    { "button.checkbox", w2s_state_button_checkbox, 13, NULL, 0 },
    { "button.3state", w2s_state_button_3state, 13, NULL, 0 },
    { "button.pushlike", w2s_state_button_pushlike, 13, NULL, 0 },
    { "button.radio", w2s_state_button_radio, 13, NULL, 0 },
    { "button.groupbox", w2s_state_button_groupbox, 13, NULL, 0 },
    { "button.split", w2s_state_button_split, 13, NULL, 0 },
    { "button.commandlink", w2s_state_button_commandlink, 13, NULL, 0 },
    { "static.text", w2s_state_static_text, 5, NULL, 0 },
    { "static.image", w2s_state_static_image, 5, NULL, 0 },
    { "static.separator", w2s_state_static_separator, 5, NULL, 0 },
    { "static.frame", w2s_state_static_frame, 5, NULL, 0 },
    { "edit.single", w2s_state_edit_single, 13, w2s_answers_edit_single, 2 },
    { "edit.password", w2s_state_edit_password, 13, w2s_answers_edit_password, 2 },
    { "edit.number", w2s_state_edit_number, 13, w2s_answers_edit_number, 2 },
    { "edit.readonly", w2s_state_edit_readonly, 13, NULL, 0 },
    { "edit.multiline", w2s_state_edit_multiline, 13, w2s_answers_edit_multiline, 9 },
    { "edit.balloon", w2s_state_edit_balloon, 13, NULL, 0 },
    { "listbox.single", w2s_state_listbox_single, 13, NULL, 0 },
    { "listbox.multi", w2s_state_listbox_multi, 13, NULL, 0 },
    { "listbox.multicolumn", w2s_state_listbox_multicolumn, 13, NULL, 0 },
    { "listbox.nosel", w2s_state_listbox_nosel, 13, NULL, 0 },
    { "combobox.dropdownlist", w2s_state_combobox_dropdownlist, 11, NULL, 0 },
    { "combobox.editable", w2s_state_combobox_editable, 11, NULL, 0 },
    { "combobox.simple", w2s_state_combobox_simple, 11, NULL, 0 },
    { "comboboxex", w2s_state_comboboxex, 10, NULL, 0 },
    { "listview.report", w2s_state_listview_report, 25, NULL, 0 },
    { "listview.icon", w2s_state_listview_icon, 25, NULL, 0 },
    { "listview.list", w2s_state_listview_list, 25, NULL, 0 },
    { "listview.checkboxes", w2s_state_listview_checkboxes, 25, NULL, 0 },
    { "listview.groups", w2s_state_listview_groups, 25, NULL, 0 },
    { "listview.empty", w2s_state_listview_empty, 25, NULL, 0 },
    { "treeview", w2s_state_treeview, 11, NULL, 0 },
    { "header", w2s_state_header, 5, NULL, 0 },
    { "tab", w2s_state_tab, 7, w2s_answers_tab, 2 },
    { "propsheet", w2s_state_propsheet, 8, NULL, 0 },
    { "propsheet.wizard", w2s_state_propsheet_wizard, 8, NULL, 0 },
    { "dialog", w2s_state_dialog, 3, NULL, 0 },
    { "toolbar", w2s_state_toolbar, 26, NULL, 0 },
    { "rebar", w2s_state_rebar, 8, w2s_answers_rebar, 1 },
    { "statusbar", w2s_state_statusbar, 7, NULL, 0 },
    { "pager", w2s_state_pager, 0, NULL, 0 },
    { "mdiclient", w2s_state_mdiclient, 0, NULL, 0 },
    { "scrollbar", w2s_state_scrollbar, 4, NULL, 0 },
    { "progress", w2s_state_progress, 8, NULL, 0 },
    { "trackbar", w2s_state_trackbar, 9, NULL, 0 },
    { "trackbar.vertical", w2s_state_trackbar_vertical, 9, NULL, 0 },
    { "updown", w2s_state_updown, 7, NULL, 0 },
    { "datetime", w2s_state_datetime, 5, NULL, 0 },
    { "monthcal", w2s_state_monthcal, 4, NULL, 0 },
    { "hotkey", w2s_state_hotkey, 2, NULL, 0 },
    { "ipaddress", w2s_state_ipaddress, 4, NULL, 0 },
    { "syslink", w2s_state_syslink, 2, NULL, 0 },
    { "animate", w2s_state_animate, 4, NULL, 0 },
    { "tooltip", w2s_state_tooltip, 14, NULL, 0 },
    { "tooltip.balloon", w2s_state_tooltip_balloon, 14, NULL, 0 },
    { "nativefont", w2s_state_nativefont, 0, NULL, 0 },
    { "messagebox", w2s_state_messagebox, 0, NULL, 0 },
    { "taskdialog", w2s_state_taskdialog, 9, NULL, 0 },
    { "filedialog.open", w2s_state_filedialog_open, 0, NULL, 0 },
    { "filedialog.save", w2s_state_filedialog_save, 0, NULL, 0 },
    { "filedialog.folder", w2s_state_filedialog_folder, 0, NULL, 0 },
    { "colordialog", w2s_state_colordialog, 0, NULL, 0 },
    { "fontdialog", w2s_state_fontdialog, 0, NULL, 0 },
    { "printdialog", w2s_state_printdialog, 0, NULL, 0 },
    { "pagesetup", w2s_state_pagesetup, 0, NULL, 0 },
    { "findreplace", w2s_state_findreplace, 0, NULL, 0 },
    { "shellabout", w2s_state_shellabout, 0, NULL, 0 },
    { "rundialog", w2s_state_rundialog, 0, NULL, 0 },
    { "pickicon", w2s_state_pickicon, 0, NULL, 0 },
    { "restartdialog", w2s_state_restartdialog, 0, NULL, 0 },
    { "fileprogress", w2s_state_fileprogress, 0, NULL, 0 },
    { "menu.bar", w2s_state_menu_bar, 0, NULL, 0 },
    { "menu.popup", w2s_state_menu_popup, 0, NULL, 0 },
    { "menu.system", w2s_state_menu_system, 0, NULL, 0 },
    { "window.frame", w2s_state_window_frame, 0, NULL, 0 },
    { "tray", w2s_state_tray, 0, NULL, 0 },
    { "notification", w2s_state_notification, 0, NULL, 0 },
    { "taskbar.progress", w2s_state_taskbar_progress, 0, NULL, 0 },
    { "attention", w2s_state_attention, 0, NULL, 0 },
    { "beep", w2s_state_beep, 0, NULL, 0 },
};

/* stock icons (map: 75-icons.yaml): a module's icon resource -> the macOS image */
struct w2s_icon_entry
{
    const WCHAR *module;
    unsigned int id;
    const char *spec;
};

static const struct w2s_icon_entry w2s_icon_entries[] =
{
    { L"user32.dll", 32512, "uttype:com.apple.application-bundle" },
    { L"user32.dll", 32513, "sf:xmark.octagon.fill;multicolor" },
    { L"user32.dll", 32514, "sf:questionmark.circle.fill;palette=white,systemBlue" },
    { L"user32.dll", 32515, "nsimage:NSCaution" },
    { L"user32.dll", 32516, "sf:info.circle.fill;palette=white,systemBlue" },
    { L"user32.dll", 32517, "uttype:com.apple.application-bundle" },
    { L"user32.dll", 32518, "sf:lock.shield.fill;palette=white,systemBlue" },
    { L"shell32.dll", 1, "uttype:public.data" },
    { L"shell32.dll", 2, "uttype:public.plain-text" },
    { L"shell32.dll", 3, "uttype:com.apple.application-bundle" },
    { L"shell32.dll", 4, "uttype:public.folder" },
    { L"shell32.dll", 5, "uttype:public.folder" },
    { L"shell32.dll", 20, "uttype:public.folder" },
    { L"shell32.dll", 29, "uttype:public.folder" },
    { L"shell32.dll", 31, "uttype:public.folder" },
    { L"shell32.dll", 6, "sf:externaldrive" },
    { L"shell32.dll", 7, "sf:externaldrive" },
    { L"shell32.dll", 8, "sf:externaldrive" },
    { L"shell32.dll", 9, "file:/" },
    { L"shell32.dll", 10, "nsimage:NSNetwork" },
    { L"shell32.dll", 11, "nsimage:NSNetwork" },
    { L"shell32.dll", 12, "sf:opticaldiscdrive" },
    { L"shell32.dll", 41, "sf:opticaldisc" },
    { L"shell32.dll", 13, "sf:memorychip" },
    { L"shell32.dll", 54, "sf:externaldrive" },
    { L"shell32.dll", 14, "nsimage:NSNetwork" },
    { L"shell32.dll", 15, "nsimage:NSNetwork" },
    { L"shell32.dll", 18, "nsimage:NSNetwork" },
    { L"shell32.dll", 19, "nsimage:NSNetwork" },
    { L"shell32.dll", 16, "nsimage:NSComputer" },
    { L"shell32.dll", 35, "file:~/Desktop" },
    { L"shell32.dll", 37, "file:/Applications" },
    { L"shell32.dll", 40, "app:com.apple.launchpad.launcher" },
    { L"shell32.dll", 36, "app:com.apple.systempreferences" },
    { L"shell32.dll", 137, "app:com.apple.systempreferences" },
    { L"shell32.dll", 22, "app:com.apple.systempreferences" },
    { L"shell32.dll", 39, "app:com.apple.FontBook" },
    { L"shell32.dll", 17, "sf:printer.fill" },
    { L"shell32.dll", 38, "sf:printer.fill" },
    { L"shell32.dll", 138, "sf:printer.fill" },
    { L"shell32.dll", 140, "sf:printer.fill" },
    { L"shell32.dll", 141, "sf:printer.fill" },
    { L"shell32.dll", 32, "nsimage:NSTrashEmpty" },
    { L"shell32.dll", 33, "nsimage:NSTrashFull" },
    { L"shell32.dll", 142, "nsimage:NSTrashFull" },
    { L"shell32.dll", 143, "nsimage:NSTrashFull" },
    { L"shell32.dll", 144, "nsimage:NSTrashFull" },
    { L"shell32.dll", 21, "sf:clock" },
    { L"shell32.dll", 23, "sf:magnifyingglass" },
    { L"shell32.dll", 46, "sf:magnifyingglass" },
    { L"shell32.dll", 134, "sf:magnifyingglass" },
    { L"shell32.dll", 135, "sf:magnifyingglass" },
    { L"shell32.dll", 24, "sf:questionmark.circle" },
    { L"shell32.dll", 25, "sf:terminal" },
    { L"shell32.dll", 160, "sf:terminal" },
    { L"shell32.dll", 26, "sf:moon.zzz" },
    { L"shell32.dll", 27, "sf:eject" },
    { L"shell32.dll", 28, "sf:power" },
    { L"shell32.dll", 49, "sf:power" },
    { L"shell32.dll", 45, "sf:rectangle.portrait.and.arrow.right" },
    { L"shell32.dll", 44, "sf:star" },
    { L"shell32.dll", 47, "sf:arrow.triangle.2.circlepath" },
    { L"shell32.dll", 48, "sf:lock.shield" },
    { L"shell32.dll", 133, "sf:doc.on.doc" },
    { L"shell32.dll", 148, "uttype:com.apple.installer-package-archive" },
    { L"shell32.dll", 151, "uttype:public.plain-text" },
    { L"shell32.dll", 152, "uttype:public.plain-text" },
    { L"shell32.dll", 153, "uttype:public.shell-script" },
    { L"shell32.dll", 154, "uttype:public.data" },
    { L"shell32.dll", 155, "uttype:public.font" },
    { L"shell32.dll", 156, "uttype:public.truetype-ttf-font" },
    { L"shell32.dll", 157, "uttype:com.adobe.postscript-font" },
    { L"shell32.dll", 165, "sf:externaldrive.badge.timemachine" },
    { L"regedit.exe", 133, "uttype:public.folder" },
    { L"regedit.exe", 132, "uttype:public.folder" },
    { L"regedit.exe", 134, "nsimage:NSComputer" },
    { L"regedit.exe", 135, "sf:textformat.abc" },
    { L"regedit.exe", 136, "sf:number" },
};

/* toolbar images (map: 75-icons.yaml toolbar_images): an image strip's image -> the macOS image */
struct w2s_toolbar_image
{
    const WCHAR *module;
    unsigned int bitmap;        /* comctl32: the standard strip's IDB_*_SMALL_COLOR; else the resource id */
    unsigned int index;
    const char *spec;
};

static const struct w2s_toolbar_image w2s_toolbar_images[] =
{
    { L"comctl32.dll", 0, 0, "sf:scissors" },
    { L"comctl32.dll", 0, 1, "sf:doc.on.doc" },
    { L"comctl32.dll", 0, 2, "sf:doc.on.clipboard" },
    { L"comctl32.dll", 0, 3, "sf:arrow.uturn.backward" },
    { L"comctl32.dll", 0, 4, "sf:arrow.uturn.forward" },
    { L"comctl32.dll", 0, 5, "sf:trash" },
    { L"comctl32.dll", 0, 6, "sf:doc.badge.plus" },
    { L"comctl32.dll", 0, 7, "sf:folder" },
    { L"comctl32.dll", 0, 8, "sf:square.and.arrow.down" },
    { L"comctl32.dll", 0, 9, "sf:doc.text.magnifyingglass" },
    { L"comctl32.dll", 0, 10, "sf:info.circle" },
    { L"comctl32.dll", 0, 11, "sf:questionmark.circle" },
    { L"comctl32.dll", 0, 12, "sf:magnifyingglass" },
    { L"comctl32.dll", 0, 13, "sf:arrow.left.arrow.right" },
    { L"comctl32.dll", 0, 14, "sf:printer" },
    { L"comctl32.dll", 4, 0, "sf:square.grid.2x2" },
    { L"comctl32.dll", 4, 1, "sf:square.grid.3x3" },
    { L"comctl32.dll", 4, 2, "sf:list.bullet" },
    { L"comctl32.dll", 4, 3, "sf:list.bullet.rectangle" },
    { L"comctl32.dll", 4, 4, "sf:textformat" },
    { L"comctl32.dll", 4, 5, "sf:arrow.up.arrow.down" },
    { L"comctl32.dll", 4, 6, "sf:calendar" },
    { L"comctl32.dll", 4, 7, "sf:doc" },
    { L"comctl32.dll", 4, 8, "sf:arrow.turn.left.up" },
    { L"comctl32.dll", 4, 9, "sf:network" },
    { L"comctl32.dll", 4, 10, "sf:xmark.circle" },
    { L"comctl32.dll", 4, 11, "sf:folder.badge.plus" },
    { L"comctl32.dll", 4, 12, "sf:ellipsis.circle" },
    { L"comctl32.dll", 8, 0, "sf:chevron.backward" },
    { L"comctl32.dll", 8, 1, "sf:chevron.forward" },
    { L"comctl32.dll", 8, 2, "sf:star" },
    { L"comctl32.dll", 8, 3, "sf:star.circle" },
    { L"comctl32.dll", 8, 4, "sf:sidebar.left" },
    { L"wordpad.exe", 100, 0, "sf:calendar.badge.clock" },
    { L"wordpad.exe", 101, 0, "sf:bold" },
    { L"wordpad.exe", 101, 1, "sf:italic" },
    { L"wordpad.exe", 101, 2, "sf:underline" },
    { L"wordpad.exe", 101, 3, "sf:paintpalette" },
    { L"wordpad.exe", 101, 4, "sf:text.alignleft" },
    { L"wordpad.exe", 101, 5, "sf:text.aligncenter" },
    { L"wordpad.exe", 101, 6, "sf:text.alignright" },
    { L"wordpad.exe", 101, 7, "sf:list.bullet" },
};

#endif
