#!/usr/bin/env python3
"""Generate runtime/pe/w2s_map_tables.h from the map.

For every entry: its id and the Windows messages in its `state_in` list, which
tell the PE side when to send the native view a fresh snapshot. Names with ANSI
and Unicode variants (LVM_INSERTITEM) get both. Every name is checked against
the wine headers, so a typo in the map fails here instead of silently never
matching.

usage: gen_runtime_tables.py <wine source tree>
"""
import glob
import os
import re
import sys

from maplib import ROOT, aslist, load_map

TOKEN = re.compile(r"^([A-Z][A-Z0-9]*_[A-Z0-9_]+)\b")


def defined_names(tree):
    names = set()
    for f in glob.glob(os.path.join(tree, "include", "*.h")) + glob.glob(os.path.join(tree, "include", "*.rh")):
        text = open(f, errors="replace").read()
        names.update(re.findall(r"#\s*define\s+(\w+)", text))
        for body in re.findall(r"\benum\b[^{;]*\{([^}]*)\}", text):
            names.update(re.findall(r"^\s*(\w+)", body, re.M))
    return names


def main():
    tree = sys.argv[1]
    names = defined_names(tree)
    m, _ = load_map()
    out, skipped = [], []
    rows = []
    for e in m["entries"]:
        msgs = []
        for item in aslist(e.get("state_in")):
            t = TOKEN.match(str(item))
            if not t:
                skipped.append(f"{e['id']}: {item}")
                continue
            n = t.group(1)
            variants = [v for v in (n + "A", n + "W") if v in names]
            if variants:
                msgs += variants
            elif n in names:
                msgs.append(n)
            else:
                sys.exit(f"{e['id']}: state_in {n} is not defined in the wine headers")
        cname = "w2s_state_" + re.sub(r"\W", "_", e["id"])
        msgs = list(dict.fromkeys(msgs))
        out.append(f"static const UINT {cname}[] = {{ {', '.join(msgs) or '0'} }};")
        rows.append(f'    {{ "{e["id"]}", {cname}, {len(msgs)} }},')
    header = f"""/* Generated by tools/gen_runtime_tables.py from map/ui-map. Don't edit. */
#ifndef W2S_MAP_TABLES_H
#define W2S_MAP_TABLES_H

struct w2s_map_entry
{{
    const char *id;
    const UINT *state_in;
    unsigned int state_in_count;
}};

{chr(10).join(out)}

static const struct w2s_map_entry w2s_map_entries[] =
{{
{chr(10).join(rows)}
}};

#endif
"""
    path = os.path.join(ROOT, "runtime", "pe", "w2s_map_tables.h")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(header)
    print(f"{path}: {len(rows)} entries; prose state_in items left out: {len(skipped)}")
    for s in skipped:
        print("  ", s)


if __name__ == "__main__":
    main()
