#!/usr/bin/env python3
"""Render map/ui-map/*.yaml into UI-MAP.md (readable tables; never edit the .md by hand)."""
import os
import re
from collections import defaultdict

from maplib import DISPOSITIONS, IDENT, ROOT, aslist, inventories, load_map, snippets, vkey

KIND_TITLES = [("control", "Controls"), ("dialog", "Dialogs"), ("menu", "Menus"), ("system", "System UI")]
RUNTIME_LABEL = {"swiftui": "SwiftUI", "appkit": "AppKit", "existing": "already native", "not_translated": "stays wine"}
GLASS_LABEL = {"explicit": "explicit glass API", "automatic": "automatic on 26+", "none": "—"}


def cell(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def short(code, n=70):
    one = re.sub(r"\s+", " ", code.strip())
    return one if len(one) <= n else one[: n - 1].rstrip() + "…"


def tiers(e):
    items = [("SwiftUI", s) for s in aslist(e.get("swiftui"))] + [("AppKit", s) for s in aslist(e.get("appkit"))]
    return sorted(items, key=lambda t: (vkey(t[1].get("since", 12)), t[0]))


def floor_cell(e):
    rt = e["runtime"]
    if rt in ("existing", "not_translated"):
        return RUNTIME_LABEL[rt]
    want = "AppKit" if rt == "appkit" else "SwiftUI"
    for kind, s in tiers(e):
        if kind == want and float(s.get("since", 12)) <= 12:
            return f"`{cell(short(s['code']))}`"
    kind, s = tiers(e)[0]
    return f"{kind}: `{cell(short(s['code']))}`"


TOKEN = re.compile(r"\.([a-z]\w*)|\b([A-Z]\w+)\b")


def toks(code):
    return ["." + a if a else b for a, b in TOKEN.findall(code)]


def newer_cell(e):
    """Name what each newer tier adds over the tiers below it."""
    out, seen = [], set()
    for kind, s in tiers(e):
        t = toks(s["code"])
        since = s.get("since", 12)
        if float(since) > 12:
            new = [x for x in dict.fromkeys(t) if x not in seen]
            newer = [x for x in new if x.lstrip(".") in NEWER]
            out.append(f"{since}: " + (", ".join(f"`{x}`" for x in (newer or new)[:3]) or "same"))
        seen.update(t)
    return cell("; ".join(out))


def win32_cell(e):
    w = e.get("win32") or {}
    bits = []
    if w.get("class"):
        bits.append(" / ".join(f"`{c}`" for c in aslist(w["class"])))
    if w.get("styles"):
        bits.append(", ".join(aslist(w["styles"])))
    if w.get("apis"):
        bits.append(", ".join(f"{a}()" if not a.startswith("I") else a for a in aslist(w["apis"])))
    return cell(" ".join(bits))


def disp_text(d):
    key = next(k for k in d if k in DISPOSITIONS)
    val = d[key]
    extra = []
    if "since" in d:
        extra.append(f"macOS {d['since']}+")
    if "fallback" in d:
        extra.append(f"before: {d['fallback']}")
    if "note" in d:
        extra.append(d["note"])
    shown = f"`{cell(short(val, 110))}`" if key in ("mod", "view", "appkit", "nscolor", "nsfont") else cell(val)
    return key, shown + (f" ({cell('; '.join(extra))})" if extra else "")


NEWER = set()


def main():
    w32, sw = inventories()
    m, _ = load_map()
    # symbols introduced after the macOS 12 floor, to label newer tiers
    for sect in ("views", "types"):
        NEWER.update(n for n, v in sw[sect].items() if vkey(v["macos"]) > vkey(12))
    # a modifier counts as newer if any of its overloads is (contextMenu(forSelectionType:) is 13)
    NEWER.update(n for n, v in sw["modifiers"].items()
                 if any(vkey(str(o).split(" ")[0]) > vkey(12) for o in v["overloads"].values()))
    for members in sw["styles"].values():
        NEWER.update(n[1:] for n, v in members.items() if vkey(v["macos"]) > vkey(12))
    NEWER.update(n for n, v in sw["appkit"].items() if vkey(v["macos"]) > vkey(12))

    entries = m["entries"]
    by_kind = defaultdict(list)
    for e in entries:
        by_kind[e["kind"]].append(e)
    claimed = {}
    for e in entries:
        for n in aslist((e.get("win32") or {}).get("styles")):
            claimed[n] = e["id"]
    part_claimed = {}
    for e in entries:
        for p in aslist((e.get("win32") or {}).get("parts")):
            part_claimed[p] = e["id"]

    L = []
    L.append("# Win32 → SwiftUI map\n")
    L.append("Generated by `tools/render_map.py` from `map/ui-map/*.yaml`. Don't edit this file; edit the YAML and re-run.\n")
    L.append(f"- Windows side: {w32['wine']['version']} (`{w32['wine']['commit'].split()[0]}`)")
    L.append(f"- macOS side: SDK {sw['sdk']['version']} ({sw['sdk']['xcode']}), {sw['sdk']['swift']}")
    ntiers = defaultdict(int)
    for e in entries:
        for _, s in tiers(e):
            ntiers[str(s.get("since", 12))] += 1
    impro = sum(1 for e in entries if e.get("improvised"))
    rts = defaultdict(int)
    for e in entries:
        rts[e["runtime"]] += 1
    nflags = sum(len(g["names"]) for g in w32["groups"] if g["kind"] in ("style", "exstyle", "flag"))
    nparts = sum(len(v) for v in w32["visual"]["parts"].values())
    L.append(f"- {len(entries)} entries: " + ", ".join(f"{n} {RUNTIME_LABEL[k]}" for k, n in rts.items()) + f"; {impro} improvised (no direct SwiftUI equivalent)")
    L.append(f"- Covered: {len({c['name'] for c in w32['classes']})} window classes, {nflags} style/flag bits, "
             f"{len(w32['apis'])} entry points, {nparts} visual parts, {len(w32['nonclient_fonts'])} system fonts "
             "(`tools/check_map.py`)")
    L.append(f"- {len(snippets(m))} Swift snippets type-check at the macOS 12 floor (`tools/typecheck_snippets.py`)")
    L.append("- Code per macOS tier: " + ", ".join(f"{k}: {v}" for k, v in sorted(ntiers.items(), key=lambda t: vkey(t[0]))))
    L.append("")
    L.append("## How to read it\n")
    L.append("- Each entry lists code per macOS tier. At run time the newest tier whose version is at or below the running macOS wins; every entry has a macOS 12 path.")
    L.append("- **Rule:** use what Apple's own apps use for that role on that macOS version. Standard controls become Liquid Glass on 26+ by themselves (\"automatic\"); explicit glass APIs are used only where Apple uses them (toolbars, floating controls).")
    L.append("- **Runs as:** SwiftUI (hosted in an NSHostingView), AppKit (where SwiftUI has no equivalent, or is built on that AppKit view), *already native* (winemac does it today), *stays wine* (the app draws it itself).")
    L.append("- **Improvised:** composed from other elements because macOS has no direct counterpart.\n")

    L.append("## Summary\n")
    for kind, title in KIND_TITLES:
        if not by_kind[kind]:
            continue
        L.append(f"### {title}\n")
        L.append("| Windows | Element | Runs as | macOS 12 | Newer tiers | Liquid Glass |")
        L.append("|---|---|---|---|---|---|")
        for e in by_kind[kind]:
            name = e["title"] + (" *(improvised)*" if e.get("improvised") else "")
            L.append(f"| {win32_cell(e)} | [{cell(name)}](#{e['id'].replace('.', '')}) | {RUNTIME_LABEL[e['runtime']]} | {floor_cell(e)} | {newer_cell(e)} | {GLASS_LABEL[e['glass']]} |")
        L.append("")

    L.append("## Entries\n")
    for kind, title in KIND_TITLES:
        for e in by_kind[kind]:
            L.append(f"### {e['title']}")
            L.append(f"<a id=\"{e['id'].replace('.', '')}\"></a>`{e['id']}` · {RUNTIME_LABEL[e['runtime']]} · Liquid Glass: {GLASS_LABEL[e['glass']]}\n")
            w = e.get("win32") or {}
            if w:
                L.append(f"- Windows: {win32_cell(e)}")
            if w.get("parts"):
                L.append(f"- Replaces visual parts: {', '.join(aslist(w['parts']))}")
            if e.get("not_translated_when"):
                L.append(f"- Stays wine when: {', '.join(e['not_translated_when'])}")
            if e.get("state_in"):
                L.append(f"- Windows → view: {', '.join(str(x) for x in e['state_in'])}")
            if e.get("events_out"):
                L.append("- View → Windows: " + "; ".join(f"{k}: {v}" for k, v in e["events_out"].items()))
            L.append("")
            for kind_, s in tiers(e):
                L.append(f"**{kind_}, macOS {s.get('since', 12)}+**\n")
                L.append("```swift")
                L.append(s["code"].rstrip())
                L.append("```\n")
            if e.get("notes"):
                L.append(e["notes"].strip() + "\n")

    L.append("## Every style and flag bit\n")
    L.append("Bits that select an entry are listed as that entry; masks, aliases and composites follow from the bits they're made of.\n")
    auto_note = {}
    for g in w32["groups"]:
        if g["kind"] not in ("style", "exstyle", "flag"):
            continue
        L.append(f"### {g['owner']} — `{g['prefix']}*` ({g['header']})\n")
        L.append("| Bit | How | Detail |")
        L.append("|---|---|---|")
        for n, v in g["names"].items():
            if n in claimed:
                L.append(f"| {n} | entry | [{claimed[n]}](#{claimed[n].replace('.', '')}) |")
            elif n in m["flags"]:
                k, t = disp_text(m["flags"][n])
                L.append(f"| {n} | {k} | {t} |")
            else:
                toks = re.findall(r"[A-Z][A-Z0-9_]+", v)
                how = "mask" if "MASK" in n else ("alias of " if len(toks) == 1 else "composite of ") + " \\| ".join(toks)
                L.append(f"| {n} | auto | {how} |")
        L.append("")

    L.append("## Every visual part (vsstyle.h)\n")
    for cls, ps in w32["visual"]["parts"].items():
        L.append(f"### {cls}\n")
        L.append("| Part | How | Detail |")
        L.append("|---|---|---|")
        for p in ps:
            key = f"{cls}/{p}"
            if key in part_claimed:
                L.append(f"| {p} | entry | [{part_claimed[key]}](#{part_claimed[key].replace('.', '')}) |")
            else:
                k, t = disp_text(m["parts"][key])
                L.append(f"| {p} | {k} | {t} |")
        L.append("")

    L.append("## Other classes, entry points and fonts\n")
    L.append("| Item | How | Detail |")
    L.append("|---|---|---|")
    for sect in ("classes", "apis", "fonts"):
        for k, d in m[sect].items():
            how, t = disp_text(d)
            L.append(f"| `{k}` | {how} | {t} |")
    L.append("")

    # SwiftUI that nothing maps to: ideas for improvising
    cited = set()
    for _, _, _, code in snippets(m):
        for mod, typ in IDENT.findall(code):
            cited.add(mod or typ)
    L.append("## SwiftUI with no Windows counterpart (yet)\n")
    L.append("Public SwiftUI views and 26+ modifiers the map doesn't use. Candidates when improvising.\n")
    L.append("| macOS | View | What it is |")
    L.append("|---|---|---|")
    for n, v in sorted(sw["views"].items(), key=lambda t: (vkey(t[1]["macos"]), t[0])):
        if n in cited or v.get("deprecated") or n.startswith(("Default", "Empty", "Tuple", "Any", "Modified", "Conditional")):
            continue
        L.append(f"| {v['macos']} | `{n}` | {cell(v.get('doc', ''))} |")
    L.append("")
    L.append("| macOS | Modifier | What it is |")
    L.append("|---|---|---|")
    for n, v in sorted(sw["modifiers"].items(), key=lambda t: (vkey(t[1]["macos"]), t[0])):
        if vkey(v["macos"]) < vkey(26) or n in cited:
            continue
        L.append(f"| {v['macos']} | `.{n}` | {cell(v.get('doc', ''))} |")
    L.append("")

    out = os.path.join(ROOT, "UI-MAP.md")
    with open(out, "w") as f:
        f.write("\n".join(L))
    print(f"{out}: {len(L)} lines")


if __name__ == "__main__":
    main()
